name: Build and Release EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies
      run: |
        choco install cmake -y
        choco install ninja -y
        git clone https://github.com/troldal/OpenXLSX.git

    - name: Build OpenXLSX
      run: |
        cd OpenXLSX
        mkdir build
        cd build
        cmake -G Ninja ..
        cmake --build . --config Release

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake -G Ninja -DOpenXLSX_DIR=../OpenXLSX/build ..
        cmake --build . --config Release

    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: add_record_exe
        path: build/Release/add_record.exe
